"use client";
import { useEffect, useState } from "react";
import { Product, Service } from "@/types";
type Item = { itemType: "product" | "service"; itemId: string; sortOrder: number; badge?: string };
export default function AdminHeroPage() {
 const [products,setProducts]=useState<Product[]>([]),[services,setServices]=useState<Service[]>([]),[items,setItems]=useState<Item[]>([]),[message,setMessage]=useState("");
 useEffect(()=>{Promise.all([fetch("/api/products").then(r=>r.json()),fetch("/api/services?admin=true").then(r=>r.json()),fetch("/api/hero?admin=true").then(r=>r.json())]).then(([p,s,h])=>{setProducts(Array.isArray(p)?p:[]);setServices(Array.isArray(s)?s:[]);setItems(Array.isArray(h)?h.map((x:any,i:number)=>({itemType:x.itemType,itemId:x.id,sortOrder:x.hero?.sortOrder??i,badge:x.hero?.badge||""})):[]);}).catch(()=>setMessage("تعذر تحميل المحتوى"));},[]);
 const selected=(type:"product"|"service",id:string)=>items.some(x=>x.itemType===type&&x.itemId===id);
 const toggle=(type:"product"|"service",id:string)=>setItems(old=>selected(type,id)?old.filter(x=>x.itemType!==type||x.itemId!==id):[...old,{itemType:type,itemId:id,sortOrder:old.length}]);
 const move=(i:number,d:number)=>setItems(old=>{const j=i+d;if(j<0||j>=old.length)return old;const next=[...old];[next[i],next[j]]=[next[j],next[i]];return next.map((x,index)=>({...x,sortOrder:index}));});
 const save=async()=>{const r=await fetch("/api/hero",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({items})});setMessage(r.ok?"تم حفظ محتوى Hero.":"تعذر الحفظ.");};
 const choices=(type:"product"|"service",list:(Product|Service)[]) => <div className="space-y-2">{list.map((x)=><label key={x.id} className="flex items-center gap-3 rounded-xl border border-slate-100 p-3 text-sm"><input type="checkbox" checked={selected(type,x.id)} onChange={()=>toggle(type,x.id)}/><img src={x.image||"/products/printing.png"} alt="" className="h-9 w-9 rounded-lg object-cover"/><span className="font-bold">{type==="product"?(x as Product).nameAr||(x as Product).name:(x as Service).titleAr||(x as Service).title}</span></label>)}</div>;
 return <div dir="rtl" className="space-y-6"><div><h1 className="text-2xl font-black">محتوى الـ Hero</h1><p className="mt-1 text-sm text-slate-500">اختر المنتجات والخدمات التي تظهر في Hero ورتبها. عند عدم الاختيار يبقى العرض الحالي فعالاً.</p></div><div className="grid gap-6 lg:grid-cols-2"><section className="rounded-3xl border bg-white p-5"><h2 className="mb-4 font-black">المنتجات</h2>{choices("product",products)}</section><section className="rounded-3xl border bg-white p-5"><h2 className="mb-4 font-black">الخدمات</h2>{choices("service",services)}</section></div><section className="rounded-3xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-black">الترتيب</h2><div className="mt-4 space-y-2">{items.map((x,i)=><div key={`${x.itemType}-${x.itemId}`} className="flex items-center gap-4 rounded-xl bg-white p-3 text-sm"><span>{i+1}</span><span className="font-bold">{x.itemType === "product" ? products.find(p=>p.id===x.itemId)?.nameAr : services.find(s=>s.id===x.itemId)?.titleAr}</span><button onClick={()=>move(i,-1)} disabled={!i}>↑</button><button onClick={()=>move(i,1)} disabled={i===items.length-1}>↓</button></div>)}</div><button onClick={save} className="mt-5 rounded-xl bg-amber-400 px-5 py-3 text-sm font-black">حفظ التغييرات</button>{message&&<p className="mt-3 text-sm font-bold">{message}</p>}</section></div>;
}
