import { Category, Product, Review } from '@/types';

export const CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Business Cards',
    nameAr: 'كروت شخصية',
    slug: 'business-cards',
    description: 'كروت شخصية فاخرة بتقنيات الورنيش البارز (Spot UV)، البصمة الذهبية والفضية، والملمس المخملي',
    image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=600&q=80',
    itemCount: 24,
  },
  {
    id: 'cat-2',
    name: 'Flyers & Pamphlets',
    nameAr: 'بروشورات ومطويات',
    slug: 'flyers',
    description: 'بروشورات تسويقية عالية الجودة بخيارات لامعة، مطفية، ومطويات متعددة الصفحات',
    image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=600&q=80',
    itemCount: 18,
  },
  {
    id: 'cat-3',
    name: 'Roll Up & Banners',
    nameAr: 'رول أب وبانرات',
    slug: 'banners',
    description: 'ستاندات رول أب قابلة للطي، بانرات فليكس، ومواد إعلانية خارجية مقاومة للعوامل الجوية',
    image: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?auto=format&fit=crop&w=600&q=80',
    itemCount: 15,
  },
  {
    id: 'cat-4',
    name: 'Stickers & Labels',
    nameAr: 'ملصقات وستيكرات',
    slug: 'stickers',
    description: 'ملصقات فينيل قص خاص (Die-Cut)، ستيكرات شفافة، وملصقات على رول للمنتجات',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
    itemCount: 32,
  },
  {
    id: 'cat-5',
    name: 'Boxes & Packaging',
    nameAr: 'علب وتغليف',
    slug: 'packaging',
    description: 'صناديق شحن مخصصة، تغليف منتجات، وعلب عرض تجارية بأسلوب احترافي',
    image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=600&q=80',
    itemCount: 20,
  },
  {
    id: 'cat-6',
    name: 'Apparel & Uniforms',
    nameAr: 'طباعة ملابس',
    slug: 'apparel',
    description: 'قمصان بولو مع تطريز مخصص، هوديز، وتيشيرتات ترويجية للمؤسسات والشركات',
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=600&q=80',
    itemCount: 14,
  },
  {
    id: 'cat-7',
    name: 'Signs & Display Stand',
    nameAr: 'لوحات إعلانية',
    slug: 'signs',
    description: 'لوحات أكريليك ثلاثية الأبعاد، شاشات إضاءة LED، وحلول عرض للمعارض والمؤتمرات',
    image: 'https://images.unsplash.com/photo-1542744094-3a3172720188?auto=format&fit=crop&w=600&q=80',
    itemCount: 12,
  },
  {
    id: 'cat-8',
    name: 'Branded Mugs & Gifts',
    nameAr: 'هدايا ومطبوعات',
    slug: 'gifts',
    description: 'أكواب سيراميك، مجموعات هدايا للشركات، أقلام، ودفاتر ملاحظات مخصصة',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
    itemCount: 28,
  },
];

export const PRODUCTS: Product[] = [
  {
    id: 'p-1',
    name: 'Ultra Luxe Business Cards',
    nameAr: 'كروت شخصية فاخرة جداً',
    slug: 'luxe-business-cards',
    categorySlug: 'business-cards',
    basePrice: 120,
    rating: 4.9,
    reviewCount: 128,
    image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'ورق قطني سميك ثقيل 400 جرام مع خيارات البصمة الذهبية/الفضية وطبقة سلوفان مخملية ناعمة.',
    badge: 'الأكثر مبيعاً',
    minQuantity: 100,
    availableSizes: ['90x55 مم (قياسي)', '85x55 مم (أوروبي)', '55x55 مم (مربع)'],
    materials: ['400 جرام مطفي فاخر', '350 جرام مخملي ناعم', '600 جرام قطن فاخر سميك جداً'],
  },
  {
    id: 'p-2',
    name: 'Luxury Deluxe Roll Up Stand',
    nameAr: 'ستاند رول أب فاخر',
    slug: 'deluxe-rollup-stand',
    categorySlug: 'banners',
    basePrice: 195,
    rating: 4.8,
    reviewCount: 84,
    image: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1626785774573-4b799315345d?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'قاعدة ألومنيوم ثقيلة وعالية التحمل مع طباعة بانر زاهية الألوان بتقنية UV غير عاكسة للضوء وحقيبة حمل.',
    badge: 'شائع',
    minQuantity: 1,
    availableSizes: ['85x200 سم', '100x200 سم', '120x200 سم'],
    materials: ['فيلم PET مانع للألتفاف', 'بانر فليكس 440 جرام', 'قماش بلوك أوت مانع للضوء'],
  },
  {
    id: 'p-3',
    name: 'Custom Product Packaging Box',
    nameAr: 'صناديق تغليف مخصصة',
    slug: 'custom-packaging-box',
    categorySlug: 'packaging',
    basePrice: 250,
    rating: 5.0,
    reviewCount: 46,
    image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'صناديق كرتون مضلع متينة ومطبوعة بالكامل من الداخل والخارج بلمسة نهائية لامعة.',
    badge: 'خيار الشركات',
    minQuantity: 50,
    availableSizes: ['صغير (20x15x10 سم)', 'وسط (30x20x12 سم)', 'كبير (40x30x15 سم)'],
    materials: ['كرتون مضلع E-Flute', 'كرتون مقوى (Rigid Board) مع حشوة مخملية', 'ورق كرافت صديق للبيئة'],
  },
  {
    id: 'p-4',
    name: 'High-Gloss Promotional Flyers',
    nameAr: 'بروشورات إعلانية عالية الجودة',
    slug: 'gloss-flyers',
    categorySlug: 'flyers',
    basePrice: 90,
    rating: 4.7,
    reviewCount: 92,
    image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80',
    ],
    description: 'بروشورات مطبوعة أوفست بألوان زاهية متوفرة بأحجام A4 وA5 وA6، وجه واحد أو وجهين.',
    minQuantity: 250,
    availableSizes: ['A5 (148x210 مم)', 'A4 (210x297 مم)', 'DL (99x210 مم)'],
    materials: ['ورق لامع 150 جرام', 'ورق مقوى فاخر 250 جرام', 'ورق حريري مطفي 170 جرام'],
  },
];

export const TESTIMONIALS: Review[] = [
  {
    id: 'rev-1',
    author: 'سامي العتيبي',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    rating: 5,
    comment: 'أدلاين السعودية أحدثت نقلة نوعية في الهوية البصرية لشركتنا! الكروت الشخصية بالبصمة الذهبية وبانرات المعرض تم تسليمها بإتقان ودقة عالية خلال 48 ساعة.',
    date: '2026-06-15',
    verifiedPurchase: true,
  },
  {
    id: 'rev-2',
    author: 'نورة الغامدي',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
    rating: 5,
    comment: 'حاسبة الأسعار الفورية وفرت علينا الكثير من الوقت. طلبنا 1,000 صندوق تغليف مخصص وكانت جودة الطباعة والتفاصيل فوق التوقعات.',
    date: '2026-07-02',
    verifiedPurchase: true,
  },
  {
    id: 'rev-3',
    author: 'فهد الدوسري',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    rating: 5,
    comment: 'خدمة استثنائية! قام فريق العمل بمساعدتنا واعتماد ملفات التصميم بكل سلاسة. سنقوم بالتأكيد بإعادة الطلب لجميع حملاتنا القادمة.',
    date: '2026-07-10',
    verifiedPurchase: true,
  },
];

export const FAQS = [
  {
    question: 'ما هي سرعة توصيل طلبات الطباعة في المملكة العربية السعودية؟',
    answer: 'تستغرق عملية الإنتاج والتوصيل القياسية من 2 إلى 4 أيام عمل في جميع المدن الرئيسية (الرياض، جدة، الدمام). كما نوفر خدمة التوصيل السريع في اليوم التالي للكروت الشخصية والبانرات العاجلة.',
  },
  {
    question: 'ما هي صيغ التصاميم المقبولة للطباعة المخصصة؟',
    answer: 'نقبل ملفات PDF عالية الدقة، وAI (Adobe Illustrator)، وPSD، وPNG (بحد أدنى 300 DPI مع هامش قص 3 مم وبنظام ألوان CMYK).',
  },
  {
    question: 'هل يمكنني طلب عينة تجريبية قبل البدء بالطباعة الكلية؟',
    answer: 'نعم! للطلبات ذات الكميات الكبيرة أو التغليف المخصص، يمكنك اعتماد عينة رقمية عبر لوحة التحكم الخاصة بك أو طلب حزمة عينات فعلية.',
  },
  {
    question: 'كيف تعمل حاسبة الأسعار الديناميكية؟',
    answer: 'ببساطة حدد خامة الورق، الأبعاد، نوع السلوفان، والكمية المطلوبة. يقوم النظام بتحديث سعر القطعة والتكلفة الإجمالية تلقائياً مع تطبيق خصومات الكمية في الوقت الفعلي.',
  },
];

export const BRANDS = [
  'شركاء أرامكو', 'موردي سابك', 'STC للأعمال', 'موسم الرياض', 'نيوم البيئية', 'مجموعة الراجحي'
];