import mongoose from "mongoose";
import { NextResponse } from "next/server";
import { connectToDatabase } from "@/lib/mongodb";
import { requireAdmin } from "@/lib/requireAdmin";
import { serializeDocument } from "@/lib/serializers";
import Exhibition from "@/models/Exhibition";
export async function GET(request: Request, context: RouteContext<"/api/exhibitions/[id]">) { await connectToDatabase(); const { id } = await context.params; const admin = new URL(request.url).searchParams.get("admin") === "true"; if (admin) { const auth = await requireAdmin(); if (auth.response) return auth.response; } const filter = mongoose.Types.ObjectId.isValid(id) ? { _id: id } : { slug: id }; const exhibition = await Exhibition.findOne(admin ? filter : { ...filter, active: true }); return exhibition ? NextResponse.json(serializeDocument(exhibition)) : NextResponse.json({ message: "المعرض غير موجود" }, { status: 404 }); }
export async function PUT(request: Request, context: RouteContext<"/api/exhibitions/[id]">) { const auth = await requireAdmin(); if (auth.response) return auth.response; try { const { id } = await context.params; const body = await request.json(); if (body.endDate && body.date && new Date(body.endDate) < new Date(body.date)) return NextResponse.json({ message: "تاريخ النهاية يجب أن يكون بعد تاريخ البداية." }, { status: 400 }); await connectToDatabase(); const exhibition = await Exhibition.findByIdAndUpdate(id, body, { new: true, runValidators: true }); return exhibition ? NextResponse.json(serializeDocument(exhibition)) : NextResponse.json({ message: "المعرض غير موجود" }, { status: 404 }); } catch (error: unknown) { const duplicate = error instanceof Error && "code" in error && (error as { code?: number }).code === 11000; return NextResponse.json({ message: duplicate ? "هذا الرابط مستخدم بالفعل." : "تعذر تحديث المعرض" }, { status: duplicate ? 409 : 500 }); } }
export const PATCH = PUT;
export async function DELETE(_request: Request, context: RouteContext<"/api/exhibitions/[id]">) { const auth = await requireAdmin(); if (auth.response) return auth.response; await connectToDatabase(); const { id } = await context.params; const result = await Exhibition.findByIdAndDelete(id); return result ? new NextResponse(null, { status: 204 }) : NextResponse.json({ message: "المعرض غير موجود" }, { status: 404 }); }
